# Generated by Django 3.2.7 on 2021-09-21 14:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('voter_id', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', editable=False, max_length=255)),
                ('address', models.CharField(blank=True, default='', editable=False, max_length=255)),
                ('place', models.CharField(blank=True, default='', editable=False, max_length=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('is_precise', models.BooleanField(default=False)),
                ('prefix', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField()),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('st', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
                ('zone', models.IntegerField()),
                ('address_json', models.JSONField(blank=True, null=True)),
                ('geocode', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
