# Generated by Django 3.2.7 on 2021-09-21 15:40

from django.db import migrations, models
import django.utils.timezone
import hashid_field.field
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('voterapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='address_json',
        ),
        migrations.AddField(
            model_name='voter',
            name='gender',
            field=models.IntegerField(choices=[(10, 'Male'), (20, 'Female'), (30, 'Unknown')], null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='party',
            field=models.IntegerField(choices=[(10, 'Unaffiliated'), (20, 'Republican'), (30, 'Democratic'), (40, 'Libertarian'), (50, 'Constitution')], null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='voter',
            name='registration',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', auto_created=True, min_length=7, prefix='', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='zone',
            field=models.IntegerField(choices=[(1, 'Zone One'), (2, 'Zone Two'), (3, 'Zone Three'), (4, 'Zone Four'), (5, 'Zone Five')], null=True),
        ),
    ]
