# Generated by Django 3.2.7 on 2021-09-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voterapi', '0003_auto_20210921_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='registration',
            field=models.DateField(null=True),
        ),
    ]
