# Generated by Django 3.2.7 on 2021-09-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voterapi', '0004_alter_voter_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(10, 'Male'), (20, 'Female'), (30, 'Unknown')], null=True),
        ),
    ]
