# Generated by Django 3.2.7 on 2021-09-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voterapi', '0005_alter_voter_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='precinct',
            field=models.IntegerField(null=True),
        ),
    ]
