# Generated by Django 3.2.7 on 2021-09-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voterapi', '0006_voter_precinct'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
