# Generated by Django 3.2.7 on 2021-09-22 00:09

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voterapi', '0007_voter_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
