# Generated by Django 3.2.9 on 2021-11-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='voter_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
