# Generated by Django 3.2.10 on 2022-02-09 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_voter_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address_json',
        ),
        migrations.RemoveField(
            model_name='account',
            name='address_raw',
        ),
    ]
