# Generated by Django 3.2.4 on 2021-07-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210616_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_steering',
            field=models.BooleanField(default=False),
        ),
    ]
