# Generated by Django 3.2.10 on 2022-02-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220208_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='address_too',
            new_name='address',
        ),
    ]
