# Generated by Django 3.2.10 on 2022-02-24 20:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_address_too_account_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ('num',)},
        ),
        migrations.AlterField(
            model_name='issue',
            name='recipient_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='issue',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
