# Generated by Django 4.0.3 on 2022-03-11 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220224_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_steering',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_vip',
        ),
        migrations.RemoveField(
            model_name='school',
            name='nurse_email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='nurse_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='exemption',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
