# Generated by Django 4.0.3 on 2022-05-18 23:04

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_account_is_steering_remove_account_is_vip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='enrollment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='app.zone'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('kind', models.IntegerField(choices=[(10, 'Elementary School'), (20, 'Middle School'), (30, 'High School')], default=0)),
                ('school_raw', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='app.school')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
