# Generated by Django 3.2.6 on 2021-08-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0007_issue_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpokenComment',
            new_name='VideoComment',
        ),
        migrations.AlterModelOptions(
            name='videocomment',
            options={'verbose_name': 'Video Comment', 'verbose_name_plural': 'Video Comments'},
        ),
    ]
