# Generated by Django 4.0.4 on 2022-05-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_staff_kind_school_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='capacity',
            new_name='size',
        ),
    ]
