# Generated by Django 3.2.6 on 2021-08-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210803_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_spouse',
            field=models.BooleanField(default=False),
        ),
    ]
