# Generated by Django 4.0.4 on 2022-05-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_capacity_school_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='capacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
