# Generated by Django 3.2.6 on 2021-08-04 17:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_event_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='recipient_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), null=True, size=None),
        ),
        migrations.AddField(
            model_name='issue',
            name='recipient_name',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
    ]
