# Generated by Django 4.0.5 on 2022-06-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_school_poly'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='gis_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
