# Generated by Django 4.0.5 on 2022-06-05 15:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_school_gis_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='poly',
        ),
        migrations.AddField(
            model_name='school',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
