# Generated by Django 3.2.6 on 2021-08-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writtencomment',
            name='comment_ptr',
        ),
        migrations.DeleteModel(
            name='VideoComment',
        ),
        migrations.DeleteModel(
            name='WrittenComment',
        ),
    ]
