# Generated by Django 4.0.5 on 2022-06-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_school_poly_school_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_traditional',
            field=models.BooleanField(default=False),
        ),
    ]
