# Generated by Django 3.2.6 on 2021-08-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210805_0519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='polymorphic_ctype',
        ),
    ]
