# Generated by Django 3.2.6 on 2021-08-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.account', unique=True),
        ),
    ]
