# Generated by Django 3.2.6 on 2021-08-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_comment_account'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('account', 'issue'), name='unique_comment'),
        ),
    ]
