# Generated by Django 3.2.6 on 2021-08-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_comment_unique_comment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendee',
            constraint=models.UniqueConstraint(fields=('account', 'event'), name='unique_attendee'),
        ),
    ]
