# Generated by Django 3.2.6 on 2021-08-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_comment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
