# Generated by Django 3.2.6 on 2021-08-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_account_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(default='avatar.png', upload_to=''),
        ),
    ]
