# Generated by Django 3.2.6 on 2021-08-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_account_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='kind',
            field=models.IntegerField(choices=[(10, 'Elementary School'), (20, 'Middle School'), (30, 'High School')], default=0),
        ),
    ]
