# Generated by Django 3.2.6 on 2021-08-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_school_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='full',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
