# Generated by Django 3.2.6 on 2021-08-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_voter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='address',
            new_name='street',
        ),
    ]
