# Generated by Django 3.2.6 on 2021-08-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_voter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='voter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='app.voter'),
        ),
    ]
