# Generated by Django 3.2.6 on 2021-08-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_account_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='zone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
