# Generated by Django 3.2.6 on 2021-08-20 12:31

import datetime
from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_account_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isat',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('school_id', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=100)),
                ('advanced', models.FloatField(blank=True, null=True)),
                ('proficient', models.FloatField(blank=True, null=True)),
                ('basic', models.FloatField(blank=True, null=True)),
                ('below', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('year', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
