# Generated by Django 3.2.6 on 2021-08-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210820_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='isat',
            name='advanced_note',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='isat',
            name='basic_note',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='isat',
            name='below_note',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='isat',
            name='proficient_note',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
