# Generated by Django 3.2.6 on 2021-09-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210820_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='story',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
