# Generated by Django 3.2.7 on 2021-09-05 22:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
