# Generated by Django 3.2.7 on 2021-09-06 10:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_zone_poly'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='poli',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='zone',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
