# Generated by Django 3.2.7 on 2021-09-06 12:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_zone_poli'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
