# Generated by Django 3.2.7 on 2021-09-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_account_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='zone',
        ),
    ]
