# Generated by Django 3.2.7 on 2021-09-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_account_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_raw',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
