# Generated by Django 3.2.7 on 2021-09-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_account_address_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
