# Generated by Django 3.2.7 on 2021-09-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_account_address_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='address_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
