# Generated by Django 3.2.7 on 2021-09-07 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20210907_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school', to='app.zone'),
        ),
    ]
