# Generated by Django 3.2.7 on 2021-09-07 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_school_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='voter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='app.voter'),
        ),
    ]
