# Generated by Django 3.2.7 on 2021-09-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_account_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='address',
        ),
    ]
