# Generated by Django 3.2.7 on 2021-09-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_remove_voter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
