# Generated by Django 3.2.7 on 2021-09-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_account_is_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='zone',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
