# Generated by Django 3.2.7 on 2021-09-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_auto_20210916_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='address',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='voter',
            name='name',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='voter',
            name='place_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
    ]
