# Generated by Django 3.2.7 on 2021-09-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_auto_20210916_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='place_id',
            new_name='place',
        ),
        migrations.AddField(
            model_name='voter',
            name='is_precise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='quality',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
    ]
