# Generated by Django 3.2.7 on 2021-09-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20210916_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='quality',
        ),
        migrations.AlterField(
            model_name='voter',
            name='place',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
