# Generated by Django 3.2.7 on 2021-09-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_auto_20210916_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='geocode',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_precise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='place',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
