# Generated by Django 3.2.7 on 2021-09-21 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20210916_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='voter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='votapi.voter'),
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
