# Generated by Django 3.2.7 on 2021-09-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20210916_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='voter',
        ),
    ]
