# Generated by Django 3.2.7 on 2021-09-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20210921_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
