# Generated by Django 3.2.7 on 2021-09-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_delete_voter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
