# Generated by Django 3.2.7 on 2021-09-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_out',
            field=models.BooleanField(default=False),
        ),
    ]
