# Generated by Django 3.2.8 on 2021-11-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_auto_20211026_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_too',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
