# Generated by Django 3.2.8 on 2021-11-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_account_address_too'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='place',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
